### ISSUE TITLE
feat: environment variable support for API key, and username

### ISSUE THREAD

**Issue by bondzula** [jeertmans/languagetool-rust#62]
### Part

Executable (CLI)

### Description

Hopefully, I'm not missing the fact that this is already supported, but similar to how we have LANGUAGETOOL_HOSTNAME, environment variables for API key, and username would be nice. I'm using this through `null-ls` and would not like to keep this info in my public dotfiles

**Comment by bondzula** [comment]
I'm not sure how or what `ltrs words` does, all my prompts result in error, how do I use it?

**Comment by jeertmans** [comment]
Oh snap! It should work like the words request documented here: https://languagetool.org/http-api/#!/default/get_words.

**Comment by bondzula** [comment]
I keep getting `request could not be properly encoded: builder error: unsupported value`, while using this example and curl `{"words":["Ltrs","languagetool-rust"]}`

This is the command I'm using `ltrs words -u {username} -k {key}`

**Comment by jeertmans** [comment]
@bondzula Would you mind testing if commands `ltrs words -u {username} -k {key}`, `ltrs words add -u {username} -k {key} {word}` and `ltrs words delete -u {username} -k {key} {word}` now work?

You can install the branch in which I'm working with:
```bash
cargo install --git https://github.com/jeertmans/languagetool-rust --branch fix-words-requests --all-features
```

**Comment by bondzula** [comment]
All of those commands now work! 👯‍♂️

**Comment by bondzula** [comment]
![image](https://user-images.githubusercontent.com/18123522/217512085-bc6965df-b2db-4311-97fa-c69fa0525912.png)

**Comment by jeertmans** [comment]
Many thanks for the help @bondzula!

**Comment by bondzula** [comment]
Thank you for fantastic project :)

**Comment by jeertmans** [comment]
Thanks @bondzula, ltrs v2.1.0 will now contain this enhancement :D
