### ISSUE TITLE
Bug: CLI auto-split does not work, limits to 1500 characters

### ISSUE THREAD

**Issue by johnblommers** [jeertmans/languagetool-rust#63]
### Description

We are told that the auto-split feature is transparent for the ltrs commandline tool. But his is not the case.

We installed as follows:

```bash
cargo install languagetool-rust --features full
```

Then we try to spell check a file larger  than 1500 characters:

```bash
ltrs --version
languagetool-rust 2.0.0

ltrs check TV.md
invalid request: Error: Your text exceeds the limit of 1500 characters (it's 3698 characters). Please submit a shorter text.
```

### Part

Executable (CLI)

### Version

languagetool-rust 2.0.0

### Platform

Linux PopOS 22.04

### Additional information

This is a first time installation.

**Comment by jeertmans** [comment]
Hello @johnblommers! Thanks for raising this issue :)
Maybe this is not documented well enough, but LTRS uses double \n to split the text.

If you do not have enough of those in your text, then split is not possible. Is it the case?

**Comment by johnblommers** [comment]
The file TV.md is a Markdown file so there are no double \n inside it ;-) Good catch! I had not seen this feature documented so good to know. 

Thanks for the speedy reply as well.

In this case the file TV.md contains a very large table so we don't see any double \n there.

Indeed after running ltrs over other Markdown files I can see that it's not well-suited to analyze them. For example it generates a rash of errors about the WHITESPACE_RULE because of an indented  numbered list. That's on the Language Tool server of course.

**Comment by jeertmans** [comment]
Well you can have double `\n\n` in a Markdown, such as in the README of this project, but it can happen that there is not.

Currently, you need to adapt the `--split-pattern <SPLIT_PATTERN>` to split of something more convenient. In the future, I hope to be able to automate the choice of this pattern.

Regarding parsing Markdown files, or any other Markup file, this is of course needs some pre-processing, not performed by LTRS at the moment. This may be a future feature :-)
