### ISSUE TITLE
Line information for found offenses

### ISSUE THREAD

**Issue by fcsonline** [jeertmans/languagetool-rust#7]
First, thanks for this code! It is great! :clap: 

Do you know if LanguageTool API provides some information about the line where offenses appear? I'm trying to integrate `ltrs` with [Nvim null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim), but it is really hard to infer the lines. The only provided information is the `offset`, `length` and `sentence` but the information about lines is lost.

My goal is to be able to show the offenses in Nvim and provide code actions to suggest some changes:

![image](https://user-images.githubusercontent.com/135988/181446110-9d6055fb-acfa-4a1f-afb7-49ab9bed0d50.png)
![image](https://user-images.githubusercontent.com/135988/181446163-4d5020c6-9350-46b7-9187-b9da2cc8048e.png)

Right now I have something working but full of edge cases due to this missing information.

**Comment by jeertmans** [comment]
Hi @fcsonline, many thanks for the feedback!

Currently, I see two ways to handle line numbers:
1. Split lines and run a check request for each of them, so you know which match is were. As LT is multithreaded, this might be very fast.
2. Check your whole file / text, then loop over the matches and, in parallel, advance in your file / text and count the number of `\n` chars.

The second option is a bit harder but I’m planning to work on such a feature in the near future :)

Anyway, it’s great to see such work on NVIM and I would love to try it when it’s ready!

**Comment by fcsonline** [comment]
The first alternative have two main problems. The first one is that a single sentence can have a break line, and this doesn't mean it has to be analyzed separately. The second problem is that we can hit the LT api limit easily.

The second alternative you propose is the one that I'm using right now, but many edge cases appear because LT loses the break lines and all the `offsets` that I get back from the api are wrong. If the sentence is in a single line, it works, but this is just the happy path.

Imagine a text like:

```
Some phrase with 
a smal mistake. i can 
drive an car
```

I don't know if LT give you this line information, but it would be great.

**Comment by jeertmans** [comment]
I am currently working on solution number 2!
Do you have an example of edge case?
I would like to test my solution against :-)

**Comment by fcsonline** [comment]
Some test cases:

**First case:**
```
Some phrase with a smal mistake.
i can drive a car
```
Mistakes: `line: 1, offset: 20, length: 4`,  `line: 2, offset: 1, length: 1`

**Second case:**
```
Some phrase with 
a smal mistake. i can 
drive a car
```

Mistakes: `line: 2, offset: 3, length: 4`,  `line: 2, offset: 17, length: 1`

**Third case:**
```
  Some phrase with a smal
mistake.

  i can drive a car
```

Mistakes: `line: 1, offset: 22, length: 4`,  `line: 4, offset: 3, length: 1`

**Fourth case:**
```
Some phrase with a smal mistake.
i can drive a car
Some phrase with a smal mistake.
```
Mistakes: `line: 1, offset: 20, length: 4`,  `line: 2, offset: 1, length: 1`, `line: 3, offset: 20, length: 4`



I think that if you are able to make these three cases work, I'll be able to make the nvim plugin reliable. :muscle:

**Comment by jeertmans** [comment]
Hi @fcsonline ! Currently working on this.

For the moment, #8 provides a fix for the line number when use with `annotate_check`.

To try this:
```bash
cargo install --path . --all-features
xclip -o | ltrs check
```

> Note: `xclip -o` outputs what is currently held in your clipboard to the terminal. You could also use `cat some_file.txt | ltrs check`.

Also note that your example contains repeated white spaces that are considered to be errors to LT.

**Comment by jeertmans** [comment]
This is now what you can get with the `MatchPositions` iterator.

Note that the offset starts at 0, not 1 (as in your example), because I prefer to keep 0-based indexing.

You can follow the work in #10 or test it by installing directly from the git branch:
```
cargo install --git https://github.com/jeertmans/languagetool-rust --branch add-more-context-to-check-reponses --all-features
```


All your cases are passed with success:
> First case:
![image](https://user-images.githubusercontent.com/27275099/182153649-79e52137-8f2b-4aec-a799-fa03af3efb96.png)

> Second case:
![image](https://user-images.githubusercontent.com/27275099/182153796-98d37a00-2f36-4201-b7f5-c970d7c719f7.png)

> Third case:
![image](https://user-images.githubusercontent.com/27275099/182154164-49689a08-abf8-4887-a27b-aa7ae5fcc025.png)

> Fourth case:
![image](https://user-images.githubusercontent.com/27275099/182154502-83be631b-70c7-4cee-a7a0-80abb1eac63a.png)

**Comment by fcsonline** [comment]
Wow! This looks great! Checking right now.

Thank you again for your job. 🤩

**Comment by fcsonline** [comment]
If you make this information available in the `raw` mode, it will be great. :pray:

**Comment by jeertmans** [comment]
You're welcome ;-) Where do you think the information (line number, line offset) might be the best placed?

In each `match`? In each `match.context` ? ...

**Comment by fcsonline** [comment]
Maybe in `match.context` as `line` and `line_offset` or something like this.

**Comment by fcsonline** [comment]
I have been testing the latest changes with `moreContext` information, and it works perfectly. :tada: It works with diagnostics and with code actions. Check this out: [Screencast from 06-08-22 13:39:34.webm](https://user-images.githubusercontent.com/135988/183247444-9c2b6d09-4861-46b6-b6fb-da3a05b84a80.webm)

**Comment by jeertmans** [comment]
Wow very nice work @fcsonline! Are you planning on releasing something publicly?

On my side, I will soon release #10 in the next version of LTRS.

**Comment by fcsonline** [comment]
For sure! After your release, I'll create the corresponding pull request to null-ls.

**Comment by fcsonline** [comment]
It has been great to have Language Tool integration into nvim. It is something that I wanted for a while, but all solutions required big installations, but with ltrs it was trivial. 💯

Thanks again for your effort! 🙌

**Comment by fcsonline** [comment]
If you want to test it, it is in this branch: https://github.com/fcsonline/null-ls.nvim/tree/feature/add-ltrs-support

**Comment by jeertmans** [comment]
Merged #10 ! I will sure give a try soon :)

Again, many thanks for your thoughts on that!

**Comment by jeertmans** [comment]
Oops seems like I have issues with the Publish GitHub action, I might need to wait Monday before it can get fixed :/

**Comment by fcsonline** [comment]
No problem. Whenever you can. :ok_hand:

**Comment by jeertmans** [comment]
@fcsonline You can now download v0.1.1 :-)

**Comment by fcsonline** [comment]
Wow! Great!

**Comment by fcsonline** [comment]
Done! Check this out: https://github.com/jose-elias-alvarez/null-ls.nvim/pull/997

**Comment by jeertmans** [comment]
Great! Subscribing to this PR so that I can follow the development. Next step feature for LTRS is probably gonna be a easy to use integration of docker within the cli.

**Comment by fcsonline** [comment]
That would be great! Also, another thing that can be added is the step to precompile binaries for each release published. Then, the installation process is as simple as download a package.

Here you have an example: https://github.com/fcsonline/tmux-thumbs/blob/master/.github/workflows/release.yml

**Comment by jeertmans** [comment]
Done! See [v1.1.1](https://github.com/jeertmans/languagetool-rust/releases/tag/v1.1.1).
