### ISSUE TITLE
help: merged into nixpkgs

### ISSUE THREAD

**Issue by name-snrl** [jeertmans/languagetool-rust#85]
### Please explain the issue you're experiencing (with as much detail as possible):

Thank you for fast tool. My pr has been merged. The package will be available in nixpkgs soon.

https://github.com/NixOS/nixpkgs/pull/234458

**Comment by jeertmans** [comment]
Hello @name-snrl, thanks you for that!

I am not sure how to interpret this issue: is it a question?

**Comment by name-snrl** [comment]
No, I just wanted to say thank you.

**Comment by jeertmans** [comment]
Oh ok, nice! Many thanks to you :D 

what does you PR in the Nix package actually imply?

**Comment by name-snrl** [comment]
`nixpkgs` is repo, that contains all packages of `nix` package manager. My PR just add `ltrs` to `nixpkgs`. All packages in `nixpkgs` are built with `hydra` and then made available as a binary cache.

Soon it will be possible to install `ltrs` with `nix profile nixpkgs#languagetool-rust`

**Comment by jeertmans** [comment]
good to know, thanks!
